# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0003_auto_20170329_1559'),
        ('pieces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='id_museum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='museums.Museum'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piece',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
