# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pieces', '0002_auto_20170330_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='id_museum',
            new_name='museum',
        ),
    ]
