# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='museums',
            name='description',
            field=models.CharField(default=4, max_length=250),
            preserve_default=False,
        ),
    ]
