# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museums', '0002_museums_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Museums',
            new_name='Museum',
        ),
    ]
